In [8]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [2]:
data = pd.read_csv('NSE-TATAGLOBAL.csv')
data.head()

Date    Open    High     Low    Last   Close  Total Trade Quantity  \
0  28-09-2018  234.05  235.95  230.20  233.50  233.75               3069914   
1  27-09-2018  234.55  236.80  231.10  233.80  233.25               5082859   
2  26-09-2018  240.00  240.00  232.50  235.00  234.25               2240909   
3  25-09-2018  233.30  236.75  232.00  236.25  236.10               2349368   
4  24-09-2018  233.55  239.20  230.75  234.00  233.30               3423509   

   Turnover (Lacs)  
0          7162.35  
1         11859.95  
2          5248.60  
3          5503.90  
4          7999.55

In [5]:
training_set = data.iloc[:, 1:2].values
training_set[0:10]

array([[234.05],
       [234.55],
       [240.  ],
       [233.3 ],
       [233.55],
       [235.  ],
       [235.95],
       [237.9 ],
       [233.15],
       [223.45]])

In [7]:
sc = MinMaxScaler(feature_range=(0,1))
training_set_scaled = sc.fit_transform(training_set)
training_set_scaled[0:10]

array([[0.6202352 ],
       [0.62226277],
       [0.64436334],
       [0.61719384],
       [0.61820762],
       [0.62408759],
       [0.62793998],
       [0.63584753],
       [0.61658556],
       [0.57725061]])

In [9]:
X_train = []
y_train = []
for i in range(60, 2035):
    X_train.append(training_set_scaled[i-60:i, 0])
    y_train.append(training_set_scaled[i, 0])
X_train, y_train = np.array(X_train), np.array(y_train)
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))

In [ ]:
!pip install tensorflow

In [14]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers import Dense

In [15]:
model = Sequential()
model.add(LSTM(units=50,return_sequences=True,input_shape=(X_train.shape[1], 1)))
model.add(Dropout(0.2))
model.add(LSTM(units=50,return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(units=50,return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(units=50))
model.add(Dropout(0.2))
model.add(Dense(units=1))
model.compile(optimizer='adam',loss='mean_squared_error')
model.fit(X_train,y_train,epochs=100,batch_size=32)

Epoch 1/100
62/62 [==============================] - 8s 55ms/step - loss: 0.0108
Epoch 2/100
62/62 [==============================] - 3s 55ms/step - loss: 0.0031
Epoch 3/100
62/62 [==============================] - 3s 56ms/step - loss: 0.0028
Epoch 4/100
62/62 [==============================] - 3s 56ms/step - loss: 0.0026
Epoch 5/100
62/62 [==============================] - 3s 55ms/step - loss: 0.0024
Epoch 6/100
62/62 [==============================] - 4s 67ms/step - loss: 0.0024
Epoch 7/100
62/62 [==============================] - 4s 59ms/step - loss: 0.0022
Epoch 8/100
62/62 [==============================] - 3s 56ms/step - loss: 0.0020
Epoch 9/100
62/62 [==============================] - 4s 60ms/step - loss: 0.0018
Epoch 10/100
62/62 [==============================] - 4s 58ms/step - loss: 0.0022
Epoch 11/100
62/62 [==============================] - 4s 64ms/step - loss: 0.0019
Epoch 12/100
62/62 [==============================] - 4s 59ms/step - loss: 0.0019
Epoch 13/100
62/62 [=====

In [17]:
real_stock_price = data.iloc[:, 1:2].values
real_stock_price[0:10]

array([[234.05],
       [234.55],
       [240.  ],
       [233.3 ],
       [233.55],
       [235.  ],
       [235.95],
       [237.9 ],
       [233.15],
       [223.45]])

In [ ]:
dataset_total = pd.concat((dataset_train['Open'], dataset_test['Open']), axis = 0)
inputs = dataset_total[len(dataset_total) - len(dataset_test) - 60:].values
inputs = inputs.reshape(-1,1)
inputs = sc.transform(inputs)
X_test = []
for i in range(60, 76):
X_test.append(inputs[i-60:i, 0])
X_test = np.array(X_test)
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
predicted_stock_price = model.predict(X_test)
predicted_stock_price = sc.inverse_transform(predicted_stock_price)